volumes:
  booking-service-db: {}
  hotel-service-db: {}
  flight-service-db: {}

services:
  booking-service-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=booking_service
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
       - booking-service-db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  flight-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flight_service
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - flight-service-db:/data/postgres
    restart: unless-stopped

  hotel-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_service
      PGDATA: /data/postgres
    volumes:
       - hotel-service-db:/data/postgres
    restart: unless-stopped

  booking-service:
    build: ./booking_service
    ports: 
      - 4000:4000
    depends_on:
      - booking-service-db
    environment:
      - HOTEL_SERVICE_HOST=http://hotel-service:4000
      - FLIGHT_SERVICE_HOST=http://flight-service:4000
      - DATABASE_URL=ecto://postgres:postgres@booking-service-db/booking_service
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  hotel-service:
    build: ./hotel_service
    ports: 
      - 4001:4000
    depends_on:
      - hotel-service-db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@hotel-service-db/hotel_service
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  flight-service:
    ports: 
      - 4002:4000
    build: ./flight_service
    depends_on:
      - flight-service-db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@flight-service-db/flight_service
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - booking-service
      - hotel-service
      - flight-service
